export type ToolCategory = 'seo' | 'sosyal-medya' | 'reklam' | 'analitik' | 'ai';
export type PricingType = 'free' | 'paid' | 'freemium';

export interface Tool {
  id: string;
  category: ToolCategory;
  icon: string;
  name: string;
  url: string;
  pricing: PricingType;
  tr: { description: string };
  en: { description: string };
}

export const tools: Tool[] = [
  // ── SEO
  {
    id: 'ahrefs',
    category: 'seo',
    icon: '🔗',
    name: 'Ahrefs',
    url: 'https://ahrefs.com',
    pricing: 'paid',
    tr: { description: 'Backlink analizi, anahtar kelime araştırması ve rakip takibi için sektörün en güçlü SEO araçlarından biri.' },
    en: { description: 'One of the most powerful SEO tools for backlink analysis, keyword research, and competitor tracking.' },
  },
  {
    id: 'semrush',
    category: 'seo',
    icon: '📊',
    name: 'SEMrush',
    url: 'https://semrush.com',
    pricing: 'freemium',
    tr: { description: 'Kapsamlı SEO, içerik pazarlama ve reklamcılık araştırması sunan all-in-one dijital pazarlama platformu.' },
    en: { description: 'An all-in-one digital marketing platform offering comprehensive SEO, content marketing, and advertising research.' },
  },
  {
    id: 'search-console',
    category: 'seo',
    icon: '🔍',
    name: 'Google Search Console',
    url: 'https://search.google.com/search-console',
    pricing: 'free',
    tr: { description: "Sitenizin Google'daki performansını izleyin, arama sorgularını analiz edin ve teknik SEO sorunlarını tespit edin." },
    en: { description: "Monitor your site's performance on Google, analyze search queries, and identify technical SEO issues." },
  },
  {
    id: 'screaming-frog',
    category: 'seo',
    icon: '🐸',
    name: 'Screaming Frog',
    url: 'https://www.screamingfrog.co.uk/seo-spider',
    pricing: 'freemium',
    tr: { description: "Web sitenizi tarayarak kırık bağlantılar, yinelenen içerik ve teknik SEO hatalarını tespit eden güçlü bir spider aracı." },
    en: { description: 'A powerful spider tool that crawls your website to identify broken links, duplicate content, and technical SEO errors.' },
  },
  {
    id: 'pagespeed',
    category: 'seo',
    icon: '⚡',
    name: 'Google PageSpeed Insights',
    url: 'https://pagespeed.web.dev',
    pricing: 'free',
    tr: { description: "Core Web Vitals ve sayfa hızı metriklerini analiz ederek sitenizin hem mobil hem masaüstü performansını ölçer." },
    en: { description: 'Analyzes Core Web Vitals and page speed metrics to measure your site performance on both mobile and desktop.' },
  },
  // ── Sosyal Medya
  {
    id: 'hootsuite',
    category: 'sosyal-medya',
    icon: '🦉',
    name: 'Hootsuite',
    url: 'https://hootsuite.com',
    pricing: 'freemium',
    tr: { description: 'Birden fazla sosyal medya hesabını tek ekrandan yönetin, içerikleri planlayın ve performansı takip edin.' },
    en: { description: 'Manage multiple social media accounts from a single screen, schedule content, and track performance.' },
  },
  {
    id: 'buffer',
    category: 'sosyal-medya',
    icon: '📅',
    name: 'Buffer',
    url: 'https://buffer.com',
    pricing: 'freemium',
    tr: { description: 'Sade arayüzüyle sosyal medya içeriklerini planlama, yayınlama ve analiz etme işlemlerini kolaylaştırır.' },
    en: { description: 'Simplifies scheduling, publishing, and analyzing social media content with its clean interface.' },
  },
  {
    id: 'canva',
    category: 'sosyal-medya',
    icon: '🎨',
    name: 'Canva',
    url: 'https://canva.com',
    pricing: 'freemium',
    tr: { description: 'Tasarım bilgisi olmadan profesyonel sosyal medya görselleri, infografikler ve sunumlar oluşturun.' },
    en: { description: 'Create professional social media visuals, infographics, and presentations without any design skills.' },
  },
  {
    id: 'later',
    category: 'sosyal-medya',
    icon: '📸',
    name: 'Later',
    url: 'https://later.com',
    pricing: 'freemium',
    tr: { description: "Instagram ve TikTok odaklı içerik planlama aracı. Görsel takvim, en iyi yayın saati önerileri ve link-in-bio özelliği sunar." },
    en: { description: 'An Instagram and TikTok-focused content scheduling tool with a visual calendar, best time to post suggestions, and link-in-bio features.' },
  },
  {
    id: 'sprout-social',
    category: 'sosyal-medya',
    icon: '🌱',
    name: 'Sprout Social',
    url: 'https://sproutsocial.com',
    pricing: 'paid',
    tr: { description: 'Kurumsal düzeyde sosyal medya yönetimi, dinleme, analiz ve raporlama platformu.' },
    en: { description: 'An enterprise-level social media management, listening, analytics, and reporting platform.' },
  },
  // ── Reklam
  {
    id: 'google-ads',
    category: 'reklam',
    icon: '🎯',
    name: 'Google Ads',
    url: 'https://ads.google.com',
    pricing: 'paid',
    tr: { description: "Google arama, display, video ve alışveriş kampanyaları oluşturun. Arama niyetiyle hedef kitlenize ulaşın." },
    en: { description: 'Create Google search, display, video, and shopping campaigns. Reach your target audience with search intent.' },
  },
  {
    id: 'meta-ads',
    category: 'reklam',
    icon: '📘',
    name: 'Meta Ads Manager',
    url: 'https://adsmanager.facebook.com',
    pricing: 'paid',
    tr: { description: "Facebook ve Instagram'da hedef kitlenize özelleştirilmiş reklamlar sunun. Geniş hedefleme seçenekleri ve güçlü analitik sunar." },
    en: { description: 'Deliver tailored ads to your audience on Facebook and Instagram. Offers extensive targeting options and powerful analytics.' },
  },
  {
    id: 'google-ads-editor',
    category: 'reklam',
    icon: '🛠️',
    name: 'Google Ads Editor',
    url: 'https://ads.google.com/intl/tr_tr/home/tools/ads-editor/',
    pricing: 'free',
    tr: { description: "Büyük kampanya değişikliklerini çevrimdışı yapmayı sağlayan Google'ın masaüstü uygulaması. Toplu düzenleme ve import/export işlemleri." },
    en: { description: "Google's desktop application for making bulk campaign changes offline. Supports bulk editing and import/export operations." },
  },
  {
    id: 'optmyzr',
    category: 'reklam',
    icon: '🤖',
    name: 'Optmyzr',
    url: 'https://optmyzr.com',
    pricing: 'paid',
    tr: { description: "Google ve Microsoft Ads kampanyalarını optimize etmek için AI destekli otomasyon ve öneri motoru." },
    en: { description: 'An AI-powered automation and recommendation engine for optimizing Google and Microsoft Ads campaigns.' },
  },
  {
    id: 'adespresso',
    category: 'reklam',
    icon: '☕',
    name: 'AdEspresso',
    url: 'https://adespresso.com',
    pricing: 'paid',
    tr: { description: "Facebook ve Instagram reklam kampanyalarını kolaylaştıran A/B test ve yönetim platformu." },
    en: { description: 'A platform that simplifies Facebook and Instagram ad campaigns with A/B testing and management.' },
  },
  // ── Analitik
  {
    id: 'ga4',
    category: 'analitik',
    icon: '📈',
    name: 'Google Analytics 4',
    url: 'https://analytics.google.com',
    pricing: 'free',
    tr: { description: "Web ve uygulama verilerini birleştirerek kullanıcı davranışını, dönüşüm hunilerini ve ROI'yi analiz edin." },
    en: { description: "Combine web and app data to analyze user behavior, conversion funnels, and ROI." },
  },
  {
    id: 'hotjar',
    category: 'analitik',
    icon: '🔥',
    name: 'Hotjar',
    url: 'https://hotjar.com',
    pricing: 'freemium',
    tr: { description: "Isı haritaları, oturum kayıtları ve anketlerle kullanıcıların sitenizde nasıl davrandığını görsel olarak anlayın." },
    en: { description: 'Visually understand how users behave on your site with heatmaps, session recordings, and surveys.' },
  },
  {
    id: 'looker-studio',
    category: 'analitik',
    icon: '📋',
    name: 'Looker Studio',
    url: 'https://lookerstudio.google.com',
    pricing: 'free',
    tr: { description: "Google ve üçüncü taraf veri kaynaklarını bağlayarak etkileşimli dashboard'lar ve raporlar oluşturun." },
    en: { description: 'Connect Google and third-party data sources to create interactive dashboards and reports.' },
  },
  {
    id: 'clarity',
    category: 'analitik',
    icon: '🔎',
    name: 'Microsoft Clarity',
    url: 'https://clarity.microsoft.com',
    pricing: 'free',
    tr: { description: "Microsoft'un ücretsiz ısı haritası ve oturum kaydı aracı. GDPR uyumlu ve sınırsız veri kaydı sunar." },
    en: { description: "Microsoft's free heatmap and session recording tool. GDPR compliant with unlimited data recording." },
  },
  {
    id: 'mixpanel',
    category: 'analitik',
    icon: '🧪',
    name: 'Mixpanel',
    url: 'https://mixpanel.com',
    pricing: 'freemium',
    tr: { description: "Ürün ve kullanıcı davranışı analitiği için güçlü olay tabanlı takip platformu. Kohort analizi ve A/B test desteği." },
    en: { description: 'A powerful event-based tracking platform for product and user behavior analytics with cohort analysis and A/B testing.' },
  },
  // ── AI
  {
    id: 'chatgpt',
    category: 'ai',
    icon: '🤖',
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    pricing: 'freemium',
    tr: { description: "OpenAI'nin güçlü dil modeli. İçerik üretimi, metin özetleme, kod yazma ve strateji geliştirme için kullanılır." },
    en: { description: "OpenAI's powerful language model used for content creation, text summarization, coding, and strategy development." },
  },
  {
    id: 'claude',
    category: 'ai',
    icon: '🧠',
    name: 'Claude',
    url: 'https://claude.ai',
    pricing: 'freemium',
    tr: { description: "Anthropic'in uzun metin analizi ve yaratıcı içerik üretiminde öne çıkan dil modeli. Güvenli ve şeffaf AI çözümü." },
    en: { description: "Anthropic's language model that excels at long-text analysis and creative content generation. A safe and transparent AI solution." },
  },
  {
    id: 'midjourney',
    category: 'ai',
    icon: '🎨',
    name: 'Midjourney',
    url: 'https://midjourney.com',
    pricing: 'paid',
    tr: { description: "Metinden görsel üreten en gelişmiş AI araçlarından biri. Sosyal medya görselleri, reklam kreatifler ve marka materyalleri için idealdir." },
    en: { description: 'One of the most advanced AI tools for generating visuals from text. Ideal for social media visuals, ad creatives, and brand materials.' },
  },
  {
    id: 'jasper',
    category: 'ai',
    icon: '✍️',
    name: 'Jasper AI',
    url: 'https://jasper.ai',
    pricing: 'paid',
    tr: { description: "Pazarlama ve satış odaklı AI içerik üretim platformu. Blog yazıları, reklam metinleri ve e-posta kampanyaları için şablonlar sunar." },
    en: { description: 'A marketing and sales-focused AI content generation platform offering templates for blog posts, ad copy, and email campaigns.' },
  },
  {
    id: 'runway',
    category: 'ai',
    icon: '🎬',
    name: 'Runway',
    url: 'https://runwayml.com',
    pricing: 'freemium',
    tr: { description: "Video oluşturma, düzenleme ve AI efektleri için güçlü bir platform. Pazarlama videoları ve sosyal medya içerikleri üretimini hızlandırır." },
    en: { description: 'A powerful platform for video generation, editing, and AI effects. Accelerates the production of marketing videos and social media content.' },
  },
];

export function getToolsByCategory(category: ToolCategory | 'all'): Tool[] {
  if (category === 'all') return tools;
  return tools.filter((t) => t.category === category);
}
